### ISSUE TITLE
Devtools panel showing on prod with Start RC Netlify

### ISSUE THREAD

**Issue by dotnize** [TanStack/devtools#195]
### TanStack Devtools version

react-devtools 0.7.1, devtools-vite 0.3.3

### Framework/Library version

React 19, Start 132.32, `@netlify/vite-plugin-tanstack-start` 1.0.2 or `nitro` 3.0.1-alpha.0 with Netlify target preset

### Describe the bug and the steps to reproduce it

Discussed on Discord: https://discord.com/channels/719702312431386674/1423273772009656383

Devtools are showing up on production in Start RC on the Netlify. Using either the official `@netlify/vite-plugin-tanstack-start` or the new Nitro v3 plugin with Netlify target.

Works fine when building locally, we see devtools being removed in build logs:

<img width="1481" height="287" alt="Image" src="https://github.com/user-attachments/assets/82b27c37-33fa-49ed-b8ac-17d9f73804ce" />

But on Netlify build logs, nothing about devtools being removed:

<img width="1275" height="383" alt="Image" src="https://github.com/user-attachments/assets/e7e29e57-35a2-4fff-a31b-22845fe5e2a5" />

Build logs here: https://app.netlify.com/projects/tss-devtools-issue/deploys/68df68ba7ae5ecb5f1997eda

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://tss-devtools-issue.netlify.app/
https://github.com/dotnize/tss-devtools-netlify (based on start-basic-react-query)

### Screenshots or Videos (Optional)

@tanstack/devtools shows up, but the actual devtools (Router/Query) themselves are empty:
<img width="1658" height="435" alt="Image" src="https://github.com/user-attachments/assets/d26badea-fae5-4559-b563-63bd9db592a5" />

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by vseventer** [comment]
I'm encountering the same problem - Start deployed on Cloudflare (cloudflare/vite-plugin).

**Comment by piehouserat** [comment]
me too, I can see that it's doing a production build from the logs yet I end up with devtools showing in prod. tanstack start being deployed to cloudflare workers

**Comment by dotnize** [comment]
I just tried the new Nitro v3 plugin (3.0.1-alpha.0) but still deploying to Netlify, and this still happens.

But on the same Nitro v3 plugin on Vercel, it works fine and the devtools are removed.

**Comment by BauZee** [comment]
I have the same problem, deploymend on Cloudflare (cloudflare/vite-plugin)

**Comment by Christoffer-M** [comment]
Same problem here deploying using Heroku

**Comment by lotap** [comment]
Also encountering this on cloudflare. If anyone got here searching for a quick temporary solution, you can wrap the devtools in `import.meta.env.DEV`

```tsx
{import.meta.env.DEV && (
	<TanStackDevtools config={...} plugins={...} />
)}
```

Adding that shaved a little under 5kb off my total assets size, which is probably the size of the minified devtools

**Comment by AlemTuzlak** [comment]
@lotap @Christoffer-M @BauZee @dotnize @piehouserat @vseventer can you guys please check if it's resolved with this PR:
https://github.com/TanStack/devtools/pull/219#issuecomment-3421789825
you should just need to install the packages mentioned in the link comment and see if it works

**Comment by dotnize** [comment]
@AlemTuzlak I updated my reproduction repo and it's still an issue for me

https://tss-devtools-issue.netlify.app/
package.json: https://github.com/dotnize/tss-devtools-netlify/blob/main/package.json#L24-L25
build/deploy logs: https://app.netlify.com/projects/tss-devtools-issue/deploys/68f6463db6df802badf90ccc

<img width="1410" height="314" alt="Image" src="https://github.com/user-attachments/assets/fc414c65-1350-40c0-b141-8e2156c68120" />

and still not seeing anything like `Removed devtools code from ...` in the logs

**Comment by Christoffer-M** [comment]
@AlemTuzlak I also tried and no difference for me either.

**Comment by AlemTuzlak** [comment]
okay I think I got it now, should work with:
```ts
 "@tanstack/devtools-vite": "https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-vite@df24016",
    "@tanstack/react-devtools": "https://pkg.pr.new/TanStack/devtools/@tanstack/react-devtools@df24016",
```

mind confirming @Christoffer-M and @dotnize (FYI I already verified on the minimum repro that I forked and deployed to netlify, there were some caching issues for me at first)

**Comment by dotnize** [comment]
@AlemTuzlak can confirm it's fixed for me on Netlify. No idea about Cloudflare though since I don't use it.

Thank you!

**Comment by AlemTuzlak** [comment]
Closing, I think the fix will solve it on everything 🚀

**Comment by vseventer** [comment]
Confirmed working on Cloudflare for me - thanks!
